version: 0.0
os: linux
files:
  - source: /
  destination: /home/ubuntu/demo_public
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
